name: cmip6-urop
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.5
  - pandas=1.4.1
  - xarray=0.20.1
  - cartopy=0.18.0
  - zarr=2.8.1
  - nbconvert
  - fsspec
  - gcsfs
  - cftime
  - tqdm
  - ffmpeg
  - pip:
    - jupyter==1.0.0
    - jupyterhub==2.2.2